name: "foxtail"

port: 8022
logsAddress: "./logs/"

sqlite:
 path: "./storage/foxtail.db"

mysql:
 name: "root"
 host: "120.XX.XX.XX"
 port: 3306
 password: "XXXXXXXX"
 dbName: "test"
 
redis:
 host: "120.XX.XX.XX"
 port: 6379